# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/guacamole/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),guacamole)

$(call add-radio-file-sha1-checked,radio/LOGO.img,a5c74a189ab7550cc881bb4bdc47c80f761c8a41)
$(call add-radio-file-sha1-checked,radio/abl.img,abfdefe9a66bd38a0e97387c0bc068d832a43ae1)
$(call add-radio-file-sha1-checked,radio/aop.img,43d7bb417683764e6380591220a1860fac589442)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,39c1cb7fa847f4ce8be5f9eee0add2c7a1ae58f6)
$(call add-radio-file-sha1-checked,radio/cmnlib.img,0002e34869735f6d4fded289f53876497e9b1fbf)
$(call add-radio-file-sha1-checked,radio/cmnlib64.img,036bb936a23e5c232ad1d3f72facff00d95219f8)
$(call add-radio-file-sha1-checked,radio/devcfg.img,2868430855e68c345b9f446109acf34b3c62a8b2)
$(call add-radio-file-sha1-checked,radio/dsp.img,11b3b7dd677655040e539285f61fc9ea4509aa6e)
$(call add-radio-file-sha1-checked,radio/hyp.img,a9eb4a9828e65708593776c2069aa3c30dcdc263)
$(call add-radio-file-sha1-checked,radio/keymaster.img,a892e6d3aa0d78b907c9c034fcddd2793b9dbd1c)
$(call add-radio-file-sha1-checked,radio/modem.img,244481ab3ea0a9e3d901292bd9ef0a78a9abae6f)
$(call add-radio-file-sha1-checked,radio/qupfw.img,96336cd873c897a71aafd813808025a0411aeea7)
$(call add-radio-file-sha1-checked,radio/storsec.img,ee15750529fc8abeea6834876fd775dabda57b0e)
$(call add-radio-file-sha1-checked,radio/tz.img,bd6e747ffd0011b413b6b6085bf4a2deab21890e)
$(call add-radio-file-sha1-checked,radio/xbl.img,035d3dae8588011a74f253e5550e41bfdd0ce53d)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,da6a383af331a327c991e15aa34cc9cba110ef77)
endif
